### ISSUE TITLE
ERROR: Could not find a version that satisfies the requirement zipline-trader (from versions: none)

### ISSUE THREAD

**Issue by ch01ca** [shlomikushchi/zipline-trader#137]
Dear Zipline Maintainers,

pip install zipline-trader
ERROR: Could not find a version that satisfies the requirement zipline-trader (from versions: none)
ERROR: No matching distribution found for zipline-trader

Sincerely,

**Comment by ch01ca** [comment]
hello, zipline-trader is not available at pipy

**Comment by shlomikushchi** [comment]
Hi, yer it is not yet on pypi. 
it could currently only be installed with clone directly from github
