### ISSUE TITLE
scipy version

### ISSUE THREAD

**Issue by ch01ca** [shlomikushchi/zipline-trader#138]
After building docker and run zipline, it show below error.
pkg_resources.ContextualVersionConflict: (scipy 0.19.1 (/usr/local/lib/python3.6/site-packages), Requirement.parse('scipy>=1.1'), {'statsmodels'})

running pip install scipy==1.1

it works

**Comment by shlomikushchi** [comment]
I'll check that. thanks

**Comment by shlomikushchi** [comment]
updated package versions in 1.6.0
