### ISSUE TITLE
Error: no such option: --state-file

### ISSUE THREAD

**Issue by ch01ca** [shlomikushchi/zipline-trader#139]
zipline run -f ~/zipline-algos/demo.py  --state-file ~/zipline-algos/demo.state  --realtime-bar-target ~/zipline-algos/realtime-bars/ --broker ib --broker-uri localhost:7496:1232 --bundle quantopian-quandl  --data-frequency minute

Usage: zipline run [OPTIONS]
Try 'zipline run --help' for help.

Error: no such option: --state-file

# pip list
Package             Version      Location
------------------- ------------ --------
alembic             1.4.3
alpaca-trade-api    0.51.0
argon2-cffi         20.1.0
async-generator     1.10
attrs               20.2.0
backcall            0.2.0
bcolz               0.12.1
bleach              3.2.1
Bottleneck          1.3.2
certifi             2020.6.20
cffi                1.14.3
chardet             3.0.4
click               7.1.2
contextlib2         0.6.0.post1
cycler              0.10.0
cyordereddict       1.0.0
Cython              0.29.21
decorator           4.4.2
defusedxml          0.6.0
empyrical           0.5.5
entrypoints         0.3
h5py                2.10.0
idna                2.10
iexfinance          0.4.3
importlib-metadata  2.0.0
intervaltree        3.1.0
ipykernel           5.3.4
ipython             7.16.1
ipython-genutils    0.2.0
ipywidgets          7.5.1
iso3166             1.0.1
iso4217             1.6.20180829
jedi                0.17.2
Jinja2              2.11.2
jsonschema          3.2.0
jupyter             1.0.0
jupyter-client      6.1.7
jupyter-console     6.2.0
jupyter-core        4.6.3
jupyterlab-pygments 0.1.2
kiwisolver          1.2.0
Logbook             1.5.3
lru-dict            1.1.6
lxml                4.6.1
Mako                1.1.3
MarkupSafe          1.1.1
matplotlib          3.3.2
mistune             0.8.4
multipledispatch    0.6.0
nbclient            0.5.1
nbconvert           6.0.7
nbformat            5.0.8
nest-asyncio        1.4.1
networkx            1.11
notebook            6.1.4
numexpr             2.7.1
numpy               1.19.2
packaging           20.4
pandas              0.22.0
pandas-datareader   0.8.1
pandocfilters       1.4.2
parso               0.7.1
patsy               0.5.1
pexpect             4.8.0
pickleshare         0.7.5
Pillow              8.0.1
pip                 18.1
pipeline-live       0.1.9
prometheus-client   0.8.0
prompt-toolkit      3.0.8
ptyprocess          0.6.0
pycparser           2.20
Pygments            2.7.1
pyparsing           2.4.7
pyrsistent          0.17.3
python-dateutil     2.8.1
python-editor       1.0.4
python-interface    1.6.0
pytz                2020.1
pyzmq               19.0.2
qtconsole           4.7.7
QtPy                1.9.0
requests            2.24.0
requests-file       1.5.1
scipy               1.1.0
Send2Trash          1.5.0
setuptools          40.4.3
six                 1.15.0
sortedcontainers    2.2.2
SQLAlchemy          1.3.20
statsmodels         0.12.0
TA-Lib              0.4.19
tables              3.6.1
terminado           0.9.1
testpath            0.4.4
toolz               0.11.1
tornado             6.0.4
trading-calendars   2.0.0
traitlets           4.3.3
urllib3             1.25.11
wcwidth             0.2.5
webencodings        0.5.1
websocket-client    0.57.0
websockets          8.1
wheel               0.32.1
widgetsnbextension  3.5.1
zipline             1.3.0
zipline-trader      0+unknown    /zipline
zipp                3.3.1

**Comment by ch01ca** [comment]
@shlomikushchi could you have a look at this?

**Comment by shlomikushchi** [comment]
currently I support only `run_algorithm()` the command line shell will be supported in the near future
