### ISSUE TITLE
Support for IB live?

### ISSUE THREAD

**Issue by fimmugit** [shlomikushchi/zipline-trader#142]
Hello,

I just installed zipline-trader in python 3.6 env. I see ZT has alpaca api but nothing for IB. Your doc hints to support IB live trading. Is this true or just a plan? 

Sincerely,

fimmu

**Comment by fimmugit** [comment]
I downloaded a zip file from the repository and unzipped it in my download folder when I run the pip install -e . command. After a while, it said zipline-trader was installed sucessfully. However, zipline and a few others were still in the download folder with an egg.link poined from the site-package folder in my env. Did I do something wrong? Any suggestion for installation for Windows?

As for the IB question I posted above, I did see a IB test script in the test folder.

**Comment by shlomikushchi** [comment]
Hi.
A Broker is used for 2 things:
1. Get data for ingestion
2. Trading

For Trading there is an implementation for both Alapca and IB
For data, we only use the FREE data source from Alpaca

**Comment by shlomikushchi** [comment]
For installation follow one of the options here: https://zipline-trader.readthedocs.io/en/latest/index.html#

**Comment by fimmugit** [comment]
Hi, Shlomi:

Thanks for the help. I now have the trader inside site-package folder and zipline inside the trader folder. Is this expected?

Best regards

**Comment by shlomikushchi** [comment]
yes, that is expected

**Comment by fimmugit** [comment]
Hi, Shlomi:

I am trying to setup the postgres backend to run the scripts you gave in the doc and having connection issue. Would you mind to point me to a good place where I can find support to set up the backend correctly? 

Thank you very much for your help in my process of moving from zipline to ZT. 

Happy holiday!

Sean

**Comment by bcs20** [comment]
> "I just installed zipline-trader in python 3.6 env. I see ZT has alpaca api but nothing for IB. Your doc hints to support IB live trading. Is this true or just a plan?"

Still i don't see that hint in the test folder
