### ISSUE TITLE
Example

### ISSUE THREAD

**Issue by jkravets1** [shlomikushchi/zipline-trader#144]
Can you post an example of a full backtest with the statistics?

**Comment by shlomikushchi** [comment]
I will soon

**Comment by shlomikushchi** [comment]
Hi, the example on running a backtest and analyzing with pyfolio is up:
https://zipline-trader.readthedocs.io/en/latest/notebooks/backtest.html

**Comment by ch01ca** [comment]
It would be great if you can provide an example for live trading

**Comment by shlomikushchi** [comment]
I will in the near future

**Comment by shlomikushchi** [comment]
added documentation for research, backtesting and going live with zipline-trader:
https://zipline-trader.readthedocs.io/en/latest/going-live.html
