### ISSUE TITLE
IB 1-minute streaming data 

### ISSUE THREAD

**Issue by ch01ca** [shlomikushchi/zipline-trader#145]
Dear shlomikushchi

Do you have a plan to develop IB 1-minute streaming data  bundle?

You know, alpaca has already developed pylivetrader that support alpaca data and order execution.  It looks like re-invent wheels at zipline-trader.

ib data bundle is really urgent requirements.

Thanks for your great job.

**Comment by shlomikushchi** [comment]
Hi,
IB data is really slow for minute data. I will add it in the future but some things have higher priority
pylivetrader is great but it doesn't have a backtester. with zipline-trader is you could backtest and research too

**Comment by ch01ca** [comment]
Hi shlomikushchi,  Thanks for providing the clarifications.

[ib_insync](https://github.com/erdewit/ib_insync) is a great wrapper. It would save a lot of time.

**Comment by shlomikushchi** [comment]
ib_insync is great. still ib limits are hard to work with.
working with a small dataset is fine. try to get minute data for 1000s of stocks daily - impossible
