### ISSUE TITLE
Installation on Mac

### ISSUE THREAD

**Issue by life-elixir** [shlomikushchi/zipline-trader#151]
Dear Zipline Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment

<details>

* Operating System: MacOSx Catalina 
* Python Version: `$ python --version` 3.6
* Python Bitness: `$ python -c 'import math, sys;print(int(math.log(sys.maxsize + 1, 2) + 1))'`
* How did you install Zipline: (`pip`, `conda`, or `other (please explain)`) pip
* Python packages: `$ pip freeze` or `$ conda list`

</details>

Now that you know a little about me, let me tell you about the issue I am
having:

# Description of Issue

* What did you expect to happen? Install zipline-trader
* What happened instead? It cannot install bcolz after doing all of the items mentioned on the installation page

Here is how you can reproduce this issue on your machine:

## Reproduction Steps

1. I used a brand new environment 
2.
3.
...

## What steps have you taken to resolve this already?

...

# Anything else?

...

Sincerely,
`$ whoami`

**Comment by shlomikushchi** [comment]
Hi,
as mentioned in the docs, mac installation is currently an issue.
it will be resolved in the future, but other things are developed first.
if there's a community member that resolves this, please open a PR for everyone else.

**Comment by ch01ca** [comment]
Docker is the best solution

**Comment by moisesbenzan** [comment]
@shlomikushchi I can volunteer to tackle this Mac issue. Is there some place I could find more information regarding as why it doesn't work? Maybe a slack channel or the likes.

**Comment by shlomikushchi** [comment]
Hi. 
thanks. you could find us on [slack](https://join.slack.com/t/zipline-live/shared_invite/zt-2eswh6cg-RkkAfook7cvREnQfit6qGA)

**Comment by sherrytp** [comment]
Hi @shlomikushchi , I found updating the bcolz wheel solves the issues for Mac OSX. The command is 
`conda install -c conda-forge bcolz`
and then use pip. However, I'm unsure if that solves the whole problem, as I will keep you and all other users informed if there comes any issue.
