### ISSUE TITLE
Installation issue on Windows 10

### ISSUE THREAD

**Issue by gvsureshreddy** [shlomikushchi/zipline-trader#156]
Getting below error when I try to install it in windows 10 through Anaconda.
I did install latest C++ through Microsoft Visual Studio BuildTool. Not sure if any one of you experienced this or tried installing this in windows?

Thanks,
gv

==========================================================================
Installing collected packages: zipline-trader
  Running setup.py develop for zipline-trader
    ERROR: Command errored out with exit status 1:
     command: 'C:\ProgramData\Anaconda3\envs\Zipline-Trader\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\WINDOWS\\system32\\src\\zipline-trader\\setup.py'"'"'; __file__='"'"'C:\\WINDOWS\\system32\\src\\zipline-trader\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps
         cwd: C:\WINDOWS\system32\src\zipline-trader\
    Complete output (34 lines):
    running develop
    running egg_info
    writing zipline_trader.egg-info\PKG-INFO
    writing dependency_links to zipline_trader.egg-info\dependency_links.txt
    writing entry points to zipline_trader.egg-info\entry_points.txt
    writing requirements to zipline_trader.egg-info\requires.txt
    writing top-level names to zipline_trader.egg-info\top_level.txt
    reading manifest file 'zipline_trader.egg-info\SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'zipline_trader.egg-info\SOURCES.txt'
    running build_ext
    skipping 'zipline/assets\_assets.c' Cython extension (up-to-date)
    skipping 'zipline/assets\continuous_futures.c' Cython extension (up-to-date)
    skipping 'zipline/lib\adjustment.c' Cython extension (up-to-date)
    skipping 'zipline/lib\_factorize.c' Cython extension (up-to-date)
    skipping 'zipline/lib\_float64window.c' Cython extension (up-to-date)
    skipping 'zipline/lib\_int64window.c' Cython extension (up-to-date)
    skipping 'zipline/lib\_int64window.c' Cython extension (up-to-date)
    skipping 'zipline/lib\_uint8window.c' Cython extension (up-to-date)
    skipping 'zipline/lib\_labelwindow.c' Cython extension (up-to-date)
    skipping 'zipline/lib\rank.c' Cython extension (up-to-date)
    skipping 'zipline/data\_equities.c' Cython extension (up-to-date)
    skipping 'zipline/data\_adjustments.c' Cython extension (up-to-date)
    skipping 'zipline\_protocol.c' Cython extension (up-to-date)
    skipping 'zipline/finance\_finance_ext.c' Cython extension (up-to-date)
    skipping 'zipline/gens\sim_engine.c' Cython extension (up-to-date)
    skipping 'zipline/data\_minute_bar_internal.c' Cython extension (up-to-date)
    skipping 'zipline/data\_resample.c' Cython extension (up-to-date)
    skipping 'zipline/pipeline/loaders/blaze\_core.c' Cython extension (up-to-date)
    building 'zipline.assets._assets' extension
    C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.28.29333\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\ProgramData\Anaconda3\envs\Zipline-Trader\lib\site-packages\numpy\core\include -IC:\ProgramData\Anaconda3\envs\Zipline-Trader\include -IC:\ProgramData\Anaconda3\envs\Zipline-Trader\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.28.29333\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt" /Tczipline/assets\_assets.c /Fobuild\temp.win-amd64-3.6\Release\zipline/assets\_assets.obj
    _assets.c
    c1: fatal error C1083: Cannot open source file: 'zipline/assets\_assets.c': No such file or directory
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.28.29333\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\ProgramData\Anaconda3\envs\Zipline-Trader\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\WINDOWS\\system32\\src\\zipline-trader\\setup.py'"'"'; __file__='"'"'C:\\WINDOWS\\system32\\src\\zipline-trader\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.
(Zipline-Trader) PS C:\WINDOWS\system32>

**Comment by shlomikushchi** [comment]
Hi, look at the installation instructions: https://zipline-trader.readthedocs.io/en/latest/install.html
conda is not yet supported.
