### ISSUE TITLE
ingest data for user supplied list of symbols

### ISSUE THREAD

**Issue by spitzbubchen** [shlomikushchi/zipline-trader#160]
Unfortunately, the three stocks that I want to back test do not exist in the SP100, SP500, or NASDAQ100 universes so I have to ingest the ALL universe which takes forever as I want to go back a few years. Is it in anyway possible that a user can specify the specific symbols that she/he wants to ingest to save time? Sorry, I am not that familiar with zipline so I don't know if this is possible.

**Comment by shlomikushchi** [comment]
hi, currently nothing builtin. I might add it in the future.
for now you could edit the ingestion file: `alpaca_api.py`
there's a function called `list_assets()`. inside of it you could override the asset list determined by the universe.

**Comment by spitzbubchen** [comment]
Great! Now I can ingest my data in ~ 6s instead of over 3000s.

An easy to implement solution could be to just allow the user to specify a list directly in alpaca.yaml. For example, universe: ['AAPL', 'C', 'AMD', ...].

**Comment by shlomikushchi** [comment]
you got it: https://github.com/shlomikushchi/zipline-trader/pull/161
