### ISSUE TITLE
statsmodel version

### ISSUE THREAD

**Issue by mac133k** [shlomikushchi/zipline-trader#169]
I built a Docker container from the master branch. The build completed with the errors:

```
statsmodels 0.12.2 has requirement scipy>=1.1, but you'll have scipy 0.19.1 which is incompatible.
aiohttp 3.7.3 has requirement chardet<4.0,>=2.0, but you'll have chardet 4.0.0 which is incompatible.
```
This makes zipline unusable due to version conflict:
```
raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (scipy 0.19.1 (/usr/local/lib/python3.6/site-packages), Requirement.parse('scipy>=1.1'), {'statsmodels'})
```
Is there a quick fix or a workaround I could use? I tried to change version numbers for the built, but that lead to other errors.

Regards,
MS

**Comment by mac133k** [comment]
Ok, I think I fixed it by removing version numbers from the Dockerfile, so the container was built with the latest versions. One version conflict still remained: aiohttp/chardet - that was resolved by:

`!pip3 install aiohttp --upgrade`

run in the notebook on the container.

**Comment by shlomikushchi** [comment]
thanks. you should use the released version since the dev branch (master) has some issues we need to resolve.
but will fix them soon
