### ISSUE TITLE
Is custom_data_path used in zipline-trader/zipline/data/bundles/alpaca_api.py? If not, it can be removed.

### ISSUE THREAD

**Issue by rileysparsons** [shlomikushchi/zipline-trader#171]
https://github.com/shlomikushchi/zipline-trader/blob/6b6839efe5fd95d8bc3c4ad8e95dd47b543dffb8/zipline/data/bundles/alpaca_api.py#L23

**Comment by shlomikushchi** [comment]
done, thanks
