### ISSUE TITLE
Support installation using Anaconda

### ISSUE THREAD

**Issue by daraul** [shlomikushchi/zipline-trader#175]
I know you [already said anaconda isn't supported](https://github.com/shlomikushchi/zipline-trader/issues/156#issuecomment-748913943), and have already said so in the docs. However, I figured it'd at least be useful for people transitioning to this alternative that have already been using anaconda successfully to see where the project stands on that point. 

I know a little python at this point, and don't mind throwing my hand in, but I'd appreciate a point in the right direction if possible.

**Comment by shlomikushchi** [comment]
Hi,
you are welcome to add support for anaconda and open a PR.
I don't have enough experience with anaconda to do that.
I don't see a reason for this redundancy right now (pypi and anaconda)  for a private package(maintained by private users)
I've made tutorials to help out with installation, check them out in the docs
