### ISSUE TITLE
Using Alphalens notebook ValueError: Cannot pass a datetime or Timestamp with tzinfo with the tz parameter

### ISSUE THREAD

**Issue by arisliang** [shlomikushchi/zipline-trader#183]
When running Using Alphalens notebook, at `get_pricing` line, it gives error:

>ValueError                                Traceback (most recent call last)
<ipython-input-12-e99e8ffde571> in <module>
      6         asset_list,
      7         pipeline_start_date,
----> 8         end_date)
      9 prices.head()
c:\src\lycn\conda-environments\zipline-trader\src\zipline-trader\zipline\research\utils.py in get_pricing(data_portal, trading_calendar, assets, start_date, end_date, field)
     51 
     52     global END_DT
---> 53     END_DT = pd.Timestamp(end_date, tz='UTC', freq='C')
     54     start_dt = pd.Timestamp(start_date, tz='UTC', freq='C')
     55 
pandas\_libs\tslibs\timestamps.pyx in pandas._libs.tslibs.timestamps.Timestamp.__new__()
ValueError: Cannot pass a datetime or Timestamp with tzinfo with the tz parameter. Use tz_convert instead.

**Comment by arisliang** [comment]
pandas: 1.0.5

**Comment by shlomikushchi** [comment]
Hi. fixed: https://github.com/shlomikushchi/zipline-trader/commit/8910a023dbfb941a870223062645d369709b71f0
pull from the master branch
