### ISSUE TITLE
No module named 'config'

### ISSUE THREAD

**Issue by evanokeefe39** [shlomikushchi/zipline-trader#186]
Traceback (most recent call last):
  File "alpaca_api.py", line 13, in <module>
    import config
ModuleNotFoundError: No module named 'config'

<img width="613" alt="error" src="https://user-images.githubusercontent.com/40553732/111030050-2abe8d00-843b-11eb-894c-854484170f8e.PNG">

after installing 1.6.0 from pypi and running alpaca ingestion according to video tutorials can't find the config module. Curious where this module comes since it appears it implements alpaca specific logic and the pypi project only talks about generic config management features...

**Comment by evanokeefe39** [comment]
config module is there in github repo but is not present in the pypi project, need to include it in pypi release i think...

**Comment by shlomikushchi** [comment]
thanks, will check it. install it from github for now

**Comment by shlomikushchi** [comment]
fixed in v1.6.1
