### ISSUE TITLE
cannot work with IB-BRK, can it support IB-BRK for living trading? I had tried but cannot work

### ISSUE THREAD

**Issue by seiyap70** [shlomikushchi/zipline-trader#189]
![image](https://user-images.githubusercontent.com/7539640/111405721-f46b6100-870b-11eb-8d8e-e9790a101024.png)

I tried local use IbPy2, It seems like IbPy2 not work with IB Trader Workstation.

**Comment by shlomikushchi** [comment]
Hi, please follow the instruction here to get IB working: http://www.zipline-live.io/tutorial
