### ISSUE TITLE
Question: Integrating Fundamentals

### ISSUE THREAD

**Issue by tbc399** [shlomikushchi/zipline-trader#192]
Before I go off and try to reinvent the wheel, is there any "good" way to integrate fundamentals? I use pipeline-live to pull in my iex data for my pylivetrader algos, but I'd like to run some more backtests, and zt looks like my best bet so far. Would there be any way to maybe jimmy pipeline-live to work with zt, or am I looking at starting from scratch if I want fundamentals?

**Comment by shlomiku** [comment]
yes, will be added soon

**Comment by tbc399** [comment]
Okay awesome. Thanks for the quick response, and thanks for the hard work.
