### ISSUE TITLE
Error when ingesting minute data from Alpaca

### ISSUE THREAD

**Issue by ac223028** [shlomikushchi/zipline-trader#199]
File "zipline/data/bundles/alpaca_api.py", line 307, in ingest
    minute_data_generator(), assets=assets_to_sids.values(), show_progress=True)
TypeError: write() got an unexpected keyword argument 'assets'

This is the Error I get when I try to do this:

register(
        package_name,  # This is the name of the ingest package
        # api_to_bundle(interval=['1d', '1m']),
        api_to_bundle(interval=['1m']),
        # api_to_bundle(interval=['1d']),
        calendar_name='NYSE',
        start_session=start_date,
        end_session=end_date
    )

Does the field where I have package name have to be 'alpaca_api'?

**Comment by bwees** [comment]
I am also getting this issue. @shlomikushchi is minute data supported yet?

**Comment by ac223028** [comment]
I see that this issue was answered here: https://github.com/shlomikushchi/zipline-trader/issues/170#issuecomment-781317789
